export const HOMEPAGE_LOADING = 'HOMEPAGE_LOADING';
export const HOMEPAGE_LOADING_SUCCES = 'HOMEPAGE_LOADING_SUCCES';

export const ABOUTPAGE_LOADING = 'ABOUTPAGE_LOADING';
export const ABOUTPAGE_LOADING_SUCCES = 'ABOUTPAGE_LOADING_SUCCESS';